#pragma once

#define PIN_BTNINP1 2
#define PIN_BTNINP2 3
#define PIN_BTNINP3 4
#define PIN_BTNINP4 5
#define PIN_BTNINP5 6
#define PIN_BTNINP6 7
#define PIN_BTNINP7 8
#define PIN_BTNINP8 9
#define PIN_BTNINP9 0
#define PIN_BTNINP10 0
#define PIN_BTNINP11 0
#define PIN_BTNINP12 0

#define PIN_BUZZER 12

#define BTN_RECORD A2

#define BTN_DECREASEOCTAVE A0
#define BTN_INCREASEOCTAVE A3